spring.application.name=customer-service
server.port=8082


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:customer_bd

spring.cloud.discovery.enabled=true

spring.cloud.config.enabled=false
